### ISSUE TITLE
Make excess deaths viz

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/obtn#12]

**Comment by dgkeyes** [comment]
https://www.economist.com/graphic-detail/coronavirus-excess-deaths-tracker

**Comment by dgkeyes** [comment]
https://www.ft.com/content/6bd88b7d-3386-4543-b2e9-0d5c6fac846c

**Comment by dgkeyes** [comment]
@charliejhadley I'm still thinking about this so let's hold off for now.

**Comment by dgkeyes** [comment]
https://medium.com/newsworthy-se/a-fraction-of-european-regions-account-for-a-majority-of-covid-deaths-778e546765a9

**Comment by charliejhadley** [comment]
I'm going to continue to wait as it looks like you're accumulating inspiration?

**Comment by dgkeyes** [comment]
Oh yeah, I actually just put this one together. 

![image](https://user-images.githubusercontent.com/13971585/169306924-7ef455dc-50b7-456c-b0dc-91ea40e5081d.png)
