### ISSUE TITLE
Bring in COVID data

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/obtn#6]
Please save all CSV or other files to `data-raw`

Measures to use from [COVID-19 Community Profile Report - County-Level](https://healthdata.gov/dataset/COVID-19-Community-Profile-Report-County-Level/di4u-7yu6):
- Cases total
- Cases per 100k population
- Deaths
- Deaths per 100k population
- Confirmed cases in hospital
- Suspected cases in hospital
- Fully vaccinated pct (look into how it's measured)

[COVID-19 Reported Patient Impact and Hospital Capacity by Facility](https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/anag-cw7u)
- hospital_pk:zip
- inpatient_beds_used_covid_7_day_avg and any other covid specific data

Please look into whether we can get excess mortality at county level or at state level

Columns to include:
- geography
- measure
- date
- value

Please export files using:

```
use_data(obtn_oregon_counties,
         overwrite = TRUE)
```

**Comment by Cghlewis** [comment]
We will also bring in excess death by state data from The Economist: https://github.com/TheEconomist/covid-19-excess-deaths-tracker/blob/master/output-data/excess-deaths/united_states_excess_deaths.csv
